from django.contrib import admin

from .models import *

admin.site.register(Category)
admin.site.register(BlockSwivels)
admin.site.register(BopAccumulatorsWellControl)
admin.site.register(CasingTubingRunning)
admin.site.register(Cementing)
admin.site.register(CoilTubing)
admin.site.register(Compressor)
admin.site.register(DrillString)
admin.site.register(DrillingRig)
admin.site.register(EnginesGensetsSCR)
admin.site.register(FishingTool)
admin.site.register(Flowback)
admin.site.register(Frac)
admin.site.register(HandlingTool)
admin.site.register(Manifold)
admin.site.register(Miscellaneou)
admin.site.register(MudPumpsConditioning)
admin.site.register(Nitrogen)
admin.site.register(OCTG)
admin.site.register(Offshore)
admin.site.register(Pumps)
admin.site.register(Slickline)
admin.site.register(Snubbing)
admin.site.register(Subsea)
admin.site.register(TopDrive)
admin.site.register(ThruTubing)
admin.site.register(WellServiceWorkover)
admin.site.register(WellTest)
admin.site.register(Wireline)

