# Generated by Django 3.1.7 on 2021-03-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('condition', models.CharField(max_length=50, verbose_name='Condition')),
                ('quantity', models.IntegerField(verbose_name='Quantity product')),
                ('location', models.CharField(max_length=50)),
                ('data_posted', models.DateField(verbose_name='Date')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category', verbose_name='Category')),
            ],
        ),
    ]
