# Generated by Django 3.1.7 on 2021-03-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.TextField(max_length=1000)),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=50)),
                ('quatity', models.IntegerField()),
                ('location', models.TextField(max_length=100)),
                ('data_posted', models.DateField()),
                ('price', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
