# Generated by Django 3.1.7 on 2021-03-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopDrives',
            new_name='TopDrive',
        ),
    ]
