# Generated by Django 3.1.7 on 2021-03-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
