# Generated by Django 3.1.7 on 2021-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210322_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocksswivels',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bopaccumulatorswellcontrol',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='casingtubingrunning',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cementing',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='drillingrig',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='drillstring',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='enginesgensetsscr',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='fishingtool',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='flowback',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='frac',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='handlingtool',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='manifold',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='miscellaneou',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='mudpumpsconditioning',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='octg',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='offshore',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pumps',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='slickline',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='snubbing',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='subsea',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='thrutubing',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='topdrive',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='wellserviceworkover',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='welltest',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='price',
            field=models.TextField(max_length=50, verbose_name='Price'),
        ),
    ]
