# Generated by Django 3.1.7 on 2021-03-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_somemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockSwivel',
            new_name='BlockSwivels',
        ),
    ]
