# Generated by Django 3.1.7 on 2021-03-24 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210324_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocksswivels',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='bopaccumulatorswellcontrol',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='casingtubingrunning',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='cementing',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='drillingrig',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='drillstring',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='enginesgensetsscr',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='fishingtool',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='flowback',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='frac',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='handlingtool',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='manifold',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='miscellaneou',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='mudpumpsconditioning',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='octg',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='offshore',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='pumps',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='slickline',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='snubbing',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='subsea',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='thrutubing',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='topdrive',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='wellserviceworkover',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='welltest',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='wireline',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9785c7f-16ff-45c1-8bd0-016b300f41f0'), editable=False),
        ),
    ]
